# Generated by Django 5.2.1 on 2025-05-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_number', models.CharField(max_length=100, verbose_name='Номер транспорта')),
                ('dispatch_datetime', models.DateTimeField(verbose_name='Дата и время отправки')),
                ('delivery_datetime', models.DateTimeField(verbose_name='Дата и время доставки')),
                ('distance', models.CharField(max_length=50, verbose_name='Дистанция')),
                ('collector', models.CharField(blank=True, max_length=200, verbose_name='Сборщик (ФИО)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='deliveries/files/', verbose_name='Вложения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='api.cargotype', verbose_name='Тип груза')),
                ('packaging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='api.packagingtype', verbose_name='Тип упаковки')),
                ('services', models.ManyToManyField(blank=True, related_name='deliveries', to='api.service', verbose_name='Услуги')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='api.deliverystatus', verbose_name='Статус доставки')),
                ('technical_condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='api.techstatus', verbose_name='Техническое состояние')),
                ('transport_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='api.transportmodel', verbose_name='Модель транспорта')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['-dispatch_datetime'],
            },
        ),
    ]
