# Generated by Django 5.2.1 on 2025-05-11 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='packaging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='api.packagingtype', verbose_name='Тип упаковки'),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='services',
        ),
        migrations.AddField(
            model_name='delivery',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='api.service', verbose_name='Услуги'),
        ),
    ]
