# Generated by Django 5.2.1 on 2025-05-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_packaging_remove_delivery_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='services',
            new_name='service',
        ),
    ]
