# Generated by Django 5.2.1 on 2025-05-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_rename_services_delivery_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='cargo_type',
        ),
    ]
