# Generated by Django 5.2.1 on 2025-05-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_delivery_cargo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
    ]
